pacemaker = "fixed"
leader-id = 1
view-change = 1
leader-schedule = [1, 2, 3, 4]

# This is the information that each replica is given about the other replicas
[[replicas]]
id = 1
peer-address = "192.168.1.1:13371"
client-address = "192.168.1.1:23371"
pubkey = "keys/r1.key.pub"
cert = "keys/r1.crt"

[[replicas]]
id = 2
peer-address = "192.168.1.2:13372"
client-address = "192.168.1.2:23372"
pubkey = "keys/r2.key.pub"
cert = "keys/r2.crt"

[[replicas]]
id = 3
peer-address = "192.168.1.3:13373"
client-address = "192.168.1.3:23373"
pubkey = "keys/r3.key.pub"
cert = "keys/r3.crt"

[[replicas]]
id = 4
peer-address = "192.168.1.4:13374"
client-address = "192.168.1.4:23374"
pubkey = "keys/r4.key.pub"
cert = "keys/r4.crt"
