// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: internal/proto/wendy/wendy.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/relab/gorums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wendy_wendy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wendy_wendy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_internal_proto_wendy_wendy_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Index struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplicaID int32 `protobuf:"varint,1,opt,name=ReplicaID,proto3" json:"ReplicaID,omitempty"`
	Exists    bool  `protobuf:"varint,2,opt,name=Exists,proto3" json:"Exists,omitempty"`
}

func (x *Index) Reset() {
	*x = Index{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wendy_wendy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wendy_wendy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_internal_proto_wendy_wendy_proto_rawDescGZIP(), []int{1}
}

func (x *Index) GetReplicaID() int32 {
	if x != nil {
		return x.ReplicaID
	}
	return 0
}

func (x *Index) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type BlockBls struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentHash []byte         `protobuf:"bytes,1,opt,name=ParentHash,proto3" json:"ParentHash,omitempty"`
	QC         *QuorumCertBls `protobuf:"bytes,2,opt,name=QC,proto3" json:"QC,omitempty"`
	Height     int64          `protobuf:"varint,3,opt,name=Height,proto3" json:"Height,omitempty"`
	Commands   []*Command     `protobuf:"bytes,4,rep,name=Commands,proto3" json:"Commands,omitempty"`
}

func (x *BlockBls) Reset() {
	*x = BlockBls{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wendy_wendy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockBls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockBls) ProtoMessage() {}

func (x *BlockBls) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wendy_wendy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockBls.ProtoReflect.Descriptor instead.
func (*BlockBls) Descriptor() ([]byte, []int) {
	return file_internal_proto_wendy_wendy_proto_rawDescGZIP(), []int{2}
}

func (x *BlockBls) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *BlockBls) GetQC() *QuorumCertBls {
	if x != nil {
		return x.QC
	}
	return nil
}

func (x *BlockBls) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockBls) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

type PartialSigBls struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplicaID int32  `protobuf:"varint,1,opt,name=ReplicaID,proto3" json:"ReplicaID,omitempty"`
	S         []byte `protobuf:"bytes,2,opt,name=S,proto3" json:"S,omitempty"`
}

func (x *PartialSigBls) Reset() {
	*x = PartialSigBls{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wendy_wendy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartialSigBls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialSigBls) ProtoMessage() {}

func (x *PartialSigBls) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wendy_wendy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialSigBls.ProtoReflect.Descriptor instead.
func (*PartialSigBls) Descriptor() ([]byte, []int) {
	return file_internal_proto_wendy_wendy_proto_rawDescGZIP(), []int{3}
}

func (x *PartialSigBls) GetReplicaID() int32 {
	if x != nil {
		return x.ReplicaID
	}
	return 0
}

func (x *PartialSigBls) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

type PartialCertBls struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig  *PartialSigBls `protobuf:"bytes,1,opt,name=Sig,proto3" json:"Sig,omitempty"`
	Hash []byte         `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *PartialCertBls) Reset() {
	*x = PartialCertBls{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wendy_wendy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartialCertBls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialCertBls) ProtoMessage() {}

func (x *PartialCertBls) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wendy_wendy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialCertBls.ProtoReflect.Descriptor instead.
func (*PartialCertBls) Descriptor() ([]byte, []int) {
	return file_internal_proto_wendy_wendy_proto_rawDescGZIP(), []int{4}
}

func (x *PartialCertBls) GetSig() *PartialSigBls {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *PartialCertBls) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type QuorumCertBls struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig  [][]byte `protobuf:"bytes,1,rep,name=Sig,proto3" json:"Sig,omitempty"`
	Hash []byte   `protobuf:"bytes,2,opt,name=Hash,proto3" json:"Hash,omitempty"`
	I    []*Index `protobuf:"bytes,3,rep,name=I,proto3" json:"I,omitempty"`
}

func (x *QuorumCertBls) Reset() {
	*x = QuorumCertBls{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wendy_wendy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuorumCertBls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumCertBls) ProtoMessage() {}

func (x *QuorumCertBls) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wendy_wendy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumCertBls.ProtoReflect.Descriptor instead.
func (*QuorumCertBls) Descriptor() ([]byte, []int) {
	return file_internal_proto_wendy_wendy_proto_rawDescGZIP(), []int{5}
}

func (x *QuorumCertBls) GetSig() [][]byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *QuorumCertBls) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *QuorumCertBls) GetI() []*Index {
	if x != nil {
		return x.I
	}
	return nil
}

type BitVector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bits []bool `protobuf:"varint,1,rep,packed,name=Bits,proto3" json:"Bits,omitempty"`
}

func (x *BitVector) Reset() {
	*x = BitVector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wendy_wendy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BitVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitVector) ProtoMessage() {}

func (x *BitVector) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wendy_wendy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitVector.ProtoReflect.Descriptor instead.
func (*BitVector) Descriptor() ([]byte, []int) {
	return file_internal_proto_wendy_wendy_proto_rawDescGZIP(), []int{6}
}

func (x *BitVector) GetBits() []bool {
	if x != nil {
		return x.Bits
	}
	return nil
}

type NewViewBls struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QC       *QuorumCertBls `protobuf:"bytes,1,opt,name=QC,proto3" json:"QC,omitempty"`
	MultiSig *PartialSigBls `protobuf:"bytes,2,opt,name=MultiSig,proto3" json:"MultiSig,omitempty"`
	BV       *BitVector     `protobuf:"bytes,3,opt,name=BV,proto3" json:"BV,omitempty"`
}

func (x *NewViewBls) Reset() {
	*x = NewViewBls{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wendy_wendy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewViewBls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewBls) ProtoMessage() {}

func (x *NewViewBls) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wendy_wendy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewBls.ProtoReflect.Descriptor instead.
func (*NewViewBls) Descriptor() ([]byte, []int) {
	return file_internal_proto_wendy_wendy_proto_rawDescGZIP(), []int{7}
}

func (x *NewViewBls) GetQC() *QuorumCertBls {
	if x != nil {
		return x.QC
	}
	return nil
}

func (x *NewViewBls) GetMultiSig() *PartialSigBls {
	if x != nil {
		return x.MultiSig
	}
	return nil
}

func (x *NewViewBls) GetBV() *BitVector {
	if x != nil {
		return x.BV
	}
	return nil
}

type IndexPublicKeys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplicaID int32      `protobuf:"varint,1,opt,name=ReplicaID,proto3" json:"ReplicaID,omitempty"`
	BV        *BitVector `protobuf:"bytes,2,opt,name=BV,proto3" json:"BV,omitempty"`
}

func (x *IndexPublicKeys) Reset() {
	*x = IndexPublicKeys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wendy_wendy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IndexPublicKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexPublicKeys) ProtoMessage() {}

func (x *IndexPublicKeys) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wendy_wendy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexPublicKeys.ProtoReflect.Descriptor instead.
func (*IndexPublicKeys) Descriptor() ([]byte, []int) {
	return file_internal_proto_wendy_wendy_proto_rawDescGZIP(), []int{8}
}

func (x *IndexPublicKeys) GetReplicaID() int32 {
	if x != nil {
		return x.ReplicaID
	}
	return 0
}

func (x *IndexPublicKeys) GetBV() *BitVector {
	if x != nil {
		return x.BV
	}
	return nil
}

type Proof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AggSig           *PartialSigBls     `protobuf:"bytes,1,opt,name=AggSig,proto3" json:"AggSig,omitempty"`
	PublicKeyIndices []*IndexPublicKeys `protobuf:"bytes,2,rep,name=PublicKeyIndices,proto3" json:"PublicKeyIndices,omitempty"`
}

func (x *Proof) Reset() {
	*x = Proof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wendy_wendy_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proof) ProtoMessage() {}

func (x *Proof) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wendy_wendy_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proof.ProtoReflect.Descriptor instead.
func (*Proof) Descriptor() ([]byte, []int) {
	return file_internal_proto_wendy_wendy_proto_rawDescGZIP(), []int{9}
}

func (x *Proof) GetAggSig() *PartialSigBls {
	if x != nil {
		return x.AggSig
	}
	return nil
}

func (x *Proof) GetPublicKeyIndices() []*IndexPublicKeys {
	if x != nil {
		return x.PublicKeyIndices
	}
	return nil
}

var File_internal_proto_wendy_wendy_proto protoreflect.FileDescriptor

var file_internal_proto_wendy_wendy_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x77, 0x65, 0x6e, 0x64, 0x79, 0x2f, 0x77, 0x65, 0x6e, 0x64, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x67, 0x6f, 0x72, 0x75, 0x6d,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x3d, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09,
	0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x73, 0x22, 0x94, 0x01, 0x0a, 0x08, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x42, 0x6c, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x24, 0x0a, 0x02, 0x51, 0x43, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x42, 0x6c,
	0x73, 0x52, 0x02, 0x51, 0x43, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2a, 0x0a,
	0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52,
	0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x22, 0x3b, 0x0a, 0x0d, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x42, 0x6c, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x49, 0x44, 0x12, 0x0c, 0x0a, 0x01, 0x53, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x01, 0x53, 0x22, 0x4c, 0x0a, 0x0e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61,
	0x6c, 0x43, 0x65, 0x72, 0x74, 0x42, 0x6c, 0x73, 0x12, 0x26, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61,
	0x72, 0x74, 0x69, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x42, 0x6c, 0x73, 0x52, 0x03, 0x53, 0x69, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x48, 0x61, 0x73, 0x68, 0x22, 0x51, 0x0a, 0x0d, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x43, 0x65,
	0x72, 0x74, 0x42, 0x6c, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x69, 0x67, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0c, 0x52, 0x03, 0x53, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1a, 0x0a, 0x01, 0x49,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x52, 0x01, 0x49, 0x22, 0x1f, 0x0a, 0x09, 0x42, 0x69, 0x74, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x08, 0x52, 0x04, 0x42, 0x69, 0x74, 0x73, 0x22, 0x86, 0x01, 0x0a, 0x0a, 0x4e, 0x65, 0x77,
	0x56, 0x69, 0x65, 0x77, 0x42, 0x6c, 0x73, 0x12, 0x24, 0x0a, 0x02, 0x51, 0x43, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x6f, 0x72,
	0x75, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x42, 0x6c, 0x73, 0x52, 0x02, 0x51, 0x43, 0x12, 0x30, 0x0a,
	0x08, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x53,
	0x69, 0x67, 0x42, 0x6c, 0x73, 0x52, 0x08, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x69, 0x67, 0x12,
	0x20, 0x0a, 0x02, 0x42, 0x56, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x69, 0x74, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x02, 0x42,
	0x56, 0x22, 0x51, 0x0a, 0x0f, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x49, 0x44, 0x12, 0x20, 0x0a, 0x02, 0x42, 0x56, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x69, 0x74, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x02, 0x42, 0x56, 0x22, 0x79, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x2c, 0x0a,
	0x06, 0x41, 0x67, 0x67, 0x53, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x53, 0x69, 0x67,
	0x42, 0x6c, 0x73, 0x52, 0x06, 0x41, 0x67, 0x67, 0x53, 0x69, 0x67, 0x12, 0x42, 0x0a, 0x10, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x10, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x32,
	0xf7, 0x01, 0x0a, 0x05, 0x57, 0x65, 0x6e, 0x64, 0x79, 0x12, 0x38, 0x0a, 0x07, 0x50, 0x72, 0x6f,
	0x70, 0x6f, 0x73, 0x65, 0x12, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x42, 0x6c, 0x73, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x04, 0x98,
	0xb5, 0x18, 0x01, 0x12, 0x3b, 0x0a, 0x04, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x43, 0x65, 0x72, 0x74, 0x42,
	0x6c, 0x73, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x04, 0xa8, 0xb5, 0x18, 0x01,
	0x12, 0x3a, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x56, 0x69, 0x65, 0x77, 0x12, 0x11, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x65, 0x77, 0x56, 0x69, 0x65, 0x77, 0x42, 0x6c, 0x73, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x04, 0xa8, 0xb5, 0x18, 0x01, 0x12, 0x3b, 0x0a, 0x0d,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x4e, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x0c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x04, 0xa8, 0xb5, 0x18, 0x01, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x62, 0x2f, 0x68, 0x6f,
	0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_wendy_wendy_proto_rawDescOnce sync.Once
	file_internal_proto_wendy_wendy_proto_rawDescData = file_internal_proto_wendy_wendy_proto_rawDesc
)

func file_internal_proto_wendy_wendy_proto_rawDescGZIP() []byte {
	file_internal_proto_wendy_wendy_proto_rawDescOnce.Do(func() {
		file_internal_proto_wendy_wendy_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_wendy_wendy_proto_rawDescData)
	})
	return file_internal_proto_wendy_wendy_proto_rawDescData
}

var file_internal_proto_wendy_wendy_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_proto_wendy_wendy_proto_goTypes = []interface{}{
	(*Command)(nil),         // 0: proto.Command
	(*Index)(nil),           // 1: proto.Index
	(*BlockBls)(nil),        // 2: proto.BlockBls
	(*PartialSigBls)(nil),   // 3: proto.PartialSigBls
	(*PartialCertBls)(nil),  // 4: proto.PartialCertBls
	(*QuorumCertBls)(nil),   // 5: proto.QuorumCertBls
	(*BitVector)(nil),       // 6: proto.BitVector
	(*NewViewBls)(nil),      // 7: proto.NewViewBls
	(*IndexPublicKeys)(nil), // 8: proto.IndexPublicKeys
	(*Proof)(nil),           // 9: proto.Proof
	(*emptypb.Empty)(nil),   // 10: google.protobuf.Empty
}
var file_internal_proto_wendy_wendy_proto_depIdxs = []int32{
	5,  // 0: proto.BlockBls.QC:type_name -> proto.QuorumCertBls
	0,  // 1: proto.BlockBls.Commands:type_name -> proto.Command
	3,  // 2: proto.PartialCertBls.Sig:type_name -> proto.PartialSigBls
	1,  // 3: proto.QuorumCertBls.I:type_name -> proto.Index
	5,  // 4: proto.NewViewBls.QC:type_name -> proto.QuorumCertBls
	3,  // 5: proto.NewViewBls.MultiSig:type_name -> proto.PartialSigBls
	6,  // 6: proto.NewViewBls.BV:type_name -> proto.BitVector
	6,  // 7: proto.IndexPublicKeys.BV:type_name -> proto.BitVector
	3,  // 8: proto.Proof.AggSig:type_name -> proto.PartialSigBls
	8,  // 9: proto.Proof.PublicKeyIndices:type_name -> proto.IndexPublicKeys
	2,  // 10: proto.Wendy.Propose:input_type -> proto.BlockBls
	4,  // 11: proto.Wendy.Vote:input_type -> proto.PartialCertBls
	7,  // 12: proto.Wendy.NewView:input_type -> proto.NewViewBls
	9,  // 13: proto.Wendy.ProofNoCommit:input_type -> proto.Proof
	10, // 14: proto.Wendy.Propose:output_type -> google.protobuf.Empty
	10, // 15: proto.Wendy.Vote:output_type -> google.protobuf.Empty
	10, // 16: proto.Wendy.NewView:output_type -> google.protobuf.Empty
	10, // 17: proto.Wendy.ProofNoCommit:output_type -> google.protobuf.Empty
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_proto_wendy_wendy_proto_init() }
func file_internal_proto_wendy_wendy_proto_init() {
	if File_internal_proto_wendy_wendy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_wendy_wendy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wendy_wendy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Index); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wendy_wendy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockBls); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wendy_wendy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartialSigBls); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wendy_wendy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartialCertBls); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wendy_wendy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuorumCertBls); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wendy_wendy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BitVector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wendy_wendy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewViewBls); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wendy_wendy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IndexPublicKeys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wendy_wendy_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_wendy_wendy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_wendy_wendy_proto_goTypes,
		DependencyIndexes: file_internal_proto_wendy_wendy_proto_depIdxs,
		MessageInfos:      file_internal_proto_wendy_wendy_proto_msgTypes,
	}.Build()
	File_internal_proto_wendy_wendy_proto = out.File
	file_internal_proto_wendy_wendy_proto_rawDesc = nil
	file_internal_proto_wendy_wendy_proto_goTypes = nil
	file_internal_proto_wendy_wendy_proto_depIdxs = nil
}
